"""make correct_answer nullable

Revision ID: 2b99bd03ddf7
Revises: c9575151972b
Create Date: 2026-07-02 02:23:02.765080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b99bd03ddf7'
down_revision: Union[str, None] = 'c9575151972b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
